iot:
  # 使用环境变量配置，避免泄漏 -Diot.productKey=k1f4kl0qmEU -Diot.productSecret=664f57b42bffcfbf3f76e7393475263d
  product-key: k1f4kl0qmEU
  product-secret:
  device-name: luna_camera
  mqtt-host-url: ssl://${iot.iot-instance-id}.mqtt.iothub.aliyuncs.com:8883
  iot-instance-id: iot-06z00f1einee6ko
  region: cn-shanghai