spring:
  application:
    name: project-start
  profiles:
    active: dev,repo

logging:
  config: classpath:log/logback-spring.xml
  level:
    root: INFO

server:
  port: 8081

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
